### ISSUE TITLE
Analysis of metric-based study regions

### ISSUE THREAD

**Issue by jds485** [USGS-R/regional-hydrologic-forcings-ml#25]
Task list. These may be several PRs (e.g., 1st, then 2nd-end)
- [x] Create function that computes FDC-based metrics for flows from median and larger. Addressed in #28 
- [x] Create function for seasonal analysis of FDC-based metrics. Addressed in #30 
- [x] Create function for cluster analysis of resulting seasonal distributions. Addressed in #50 
- [x] Create function that visualizes resulting cluster regions. Addressed in #50 
- [ ] Create function that generates the union of selected regions and saves to shapefile. Likely will move to a new issue to explore options for combining point-based clusters into watershed-based regions

**Comment by jds485** [comment]
For seasons in which we have no events, do we want the duration of events above a % threshold for that season to be reported as 0 or as NA? The resulting seasonal average (computed across all years for a site) will be affected by 0s, but will not be affected by NAs (NAs are dropped). Treating as NA will provide a more accurate estimate of the average duration of events above the threshold in that season, so I'm leaning towards using NAs

**Comment by jds485** [comment]
Just realizing that the choice does not matter if we transform the raw seasonal durations into fractions of a year: `(season duration)/(annual total duration)`

**Comment by jds485** [comment]
I can see 2 approaches for computing the resulting seasonal metrics and I'm not sure which is best to use:
1. Period of record method: 
  - Compute the seasonal durations for each year (4*n years values)
  - Average the seasonal values over all years (4 values)
  - Compute the fraction per season (4 values)
      
2. Annual timeseries method:
  - Compute the seasonal durations for each year (4*n years values)
  - Compute the fraction per season (4*n years values)
  - Average the fractions over all years (4 values)

Any suggestions? @FlowChar, what approach did you use for previous work with seasonal metrics?

**Comment by cstillwellusgs** [comment]
Not sure I fully follow - what do you mean by "compute the fraction per season" (in both approach 1 and 2)?

**Comment by jds485** [comment]
For example, considering number of events:
fraction per season = events in season / total events for the year

**Comment by jds485** [comment]
I'm opting to close this. We are currently using separate regions for flows 50-70th percentile and flows 75th-95th percentile
